/**
 * 网络状态指纹（issue #368）。
 *
 * 为什么需要：链路变化 watcher 的事件流**不能直接当判据**——
 *  ① 事件流有周期性噪音：IPv6 RA 刷新地址 lifetime、短租期 DHCP renew 都会推送 `ip monitor` / RTM_NEWADDR，
 *     而网络其实没变。以「收到事件」为判据 = 稳态下每个限频窗口都刷一次系统 DNS 缓存，把缓存寿命永久钉在
 *     限频间隔上，解析延迟持续劣化且无任何异常日志。
 *  ② 事件流会自触发：FlowZ 自己的路由操作（mesh 出口 reconcile 的 ip rule/route、macOS 侧同类 route 调用）
 *     同样进事件流，会把限频窗口白白耗掉，随后用户真实换网的那一次反而被丢弃——正是 issue #368 要修的场景。
 *
 * 故：**事件只作为「去看一眼」的唤醒信号，是否真的变了由本模块的指纹对差判定**。指纹相同 = 什么都没发生，
 * 不刷；指纹变化 = 接口/地址真的动了，才刷。Windows 无链路事件源，直接低频轮询本指纹即可，无需子进程。
 */
import type { NetworkInterfaceInfo } from 'os';

/**
 * 由 `os.networkInterfaces()` 的结果算一枚指纹。
 *
 * 取材面（**刻意窄于「全部接口信息」**）：接口名 + 非 internal 的非 link-local 地址集合，排序后拼接。
 *  - 排除 `internal`（loopback）：它恒定存在，不携带「网络变了」的信息。
 *  - 排除 IPv6 link-local（`fe80::/10`）：由 MAC 派生、随接口存在即存在，接口 up 但尚未拿到可路由地址时
 *    只有它出现——此刻网络还没通，刷缓存没有意义；等真拿到地址会再触发一次，不会漏。
 *  - 排除 IPv4 link-local（`169.254/16`，APIPA）：与 fe80 同理——DHCP 未成功时的占位地址，此刻网络没通；
 *    不排除的话，Windows 上 DHCP 失败/恢复循环会让它反复起落，被当成真实网络变化。
 *  - 排除 `mac` / `netmask` / `cidr` 等字段：MAC 不会变；netmask 几乎总是与 address 一起变（同址重划子网
 *    罕见，且不影响 DNS 缓存正确性），纳入只增噪音面。
 *  - **保留** IPv6 privacy 临时地址（无法从本 API 区分）：其轮换周期是**天**级（temp_prefered_lft 默认 1 天），
 *    远大于限频窗口，最坏是每天多刷两次（新临时地址出现 + 旧地址到期消失），代价可忽略；
 *    为了区分它而去读 /proc 是把判据换成会腐坏的那个。
 *  - **保留** TUN 接口：TUN 起落本就是真实的网络变化，刷缓存是正确行为。
 *
 * 已知漏判（`os.networkInterfaces()` 的天花板）：「换到另一个网络但拿到同接口同地址」（两个都是
 * 192.168.1.0/24 的家/公司网、DHCP 复用旧租约、同址换 AP）与「同一租约只改 DHCP 的 DNS server 选项」——
 * 地址一字未变而上游 resolver 已换，正是最需要刷缓存的形态之一。变的东西（网关、resolver）不在本 API
 * 返回值里，故 Linux 侧另取一路判据补上（见 readLinuxResolverFingerprint），macOS/Windows 暂留为已知漏判
 * （`scutil --dns` / PowerShell 是 exec 而非文件读，成本形态不同）；三平台兜底都是 start/stop 两点无条件刷。
 *
 * @param ifaces `os.networkInterfaces()` 的返回值（注入便于单测，不在本模块内直接调用 os）。
 * @returns 稳定的指纹字符串（同一网络状态恒等，与调用顺序无关）。
 */
export function computeNetworkFingerprint(ifaces: NodeJS.Dict<NetworkInterfaceInfo[]>): string {
  const parts: string[] = [];
  for (const [name, addrs] of Object.entries(ifaces)) {
    if (!addrs) continue;
    for (const a of addrs) {
      if (a.internal) continue;
      if (a.family === 'IPv6' && a.address.toLowerCase().startsWith('fe80:')) continue;
      if (a.family === 'IPv4' && a.address.startsWith('169.254.')) continue;
      parts.push(`${name}|${a.family}|${a.address}`);
    }
  }
  // 排序：Object.entries 与内核给出的地址顺序都不保证稳定，不排序会把「顺序抖动」误判成「网络变化」。
  return parts.sort().join('\n');
}

/** 一次刷新尝试的结果分类（决定指纹基线怎么推进）。 */
export type FlushOutcome = 'flushed' | 'skipped' | 'failed' | 'rate-limited';

/**
 * 刷新尝试后的指纹基线取值。
 *
 * 只有**真正刷成功**才把基线推进到本次指纹；其余一律清空（null = 下个事件无条件刷一次）。
 * 清空而非保留旧值的理由是 A→B→A 回退：限频拦下或刷新失败期间从网络 A 换到 B 又换回 A，
 * 保留旧基线会让指纹与基线相等 → 判成「什么都没发生」而永不补刷，B 期间污染的缓存只能等 TTL 自愈
 * （正是 issue #363 的形态，规模小一号）。清空的代价只是多刷一次。
 *
 * @param dirtiedWhileInFlight 本次刷新**在飞期间**又有事件被判为「网络已变」（补刷在排）。此时哪怕本次
 *   刷成功也不能推进基线——`fingerprint` 是发起时刻的旧世界，推进它会盖掉那次判脏，A→B→A 在并发交织
 *   下复活。异步刷新 + 同步判脏共写一个基线，这是必须显式传入的第三个状态。
 */
export function nextFingerprintBaseline(
  outcome: FlushOutcome,
  fingerprint: string | undefined,
  dirtiedWhileInFlight = false
): string | null {
  if (dirtiedWhileInFlight) return null;
  if (outcome === 'flushed' && fingerprint !== undefined) return fingerprint;
  return null;
}

/** systemd-resolved 写出的**真实上游** resolver 列表。 */
const SYSTEMD_RESOLVED_RESOLV_CONF = '/run/systemd/resolve/resolv.conf';

/**
 * Linux 上游 resolver 指纹（补 computeNetworkFingerprint 看不见的那一面）。
 *
 * 取 `/run/systemd/resolve/resolv.conf` 而**不是** `/etc/resolv.conf`：后者在 systemd-resolved 环境下恒为
 * 指向 stub 的符号链接，内容永远是 `nameserver 127.0.0.53`，对「上游换了没有」零判别力（本机实测）。
 * 只取 nameserver/search 行（注释头与 `# Generated by` 之类的抖动不该算网络变化），**保留文件内次序**：
 * resolved 写出的 nameserver 次序即查询优先级，主备互换是真实的 resolver 变化。排序会把它抹平成「没变」，
 * 而两种误判的代价不对称——多刷一次只是一条命令，漏刷就是 issue #363 本身。
 *
 * 读失败（文件不存在 = 非 systemd-resolved 发行版、权限、竞态改写）一律返回空串——退化成「这一路判据不参与」，
 * 与本函数引入前的行为完全一致，不会把读不到误判成变化。
 *
 * @param readFile 注入便于单测（真实实现 = fs.readFileSync 的 utf-8 读）。
 */
export function readLinuxResolverFingerprint(readFile: (p: string) => string): string {
  let raw: string;
  try {
    raw = readFile(SYSTEMD_RESOLVED_RESOLV_CONF);
  } catch {
    return '';
  }
  const lines = raw
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.startsWith('nameserver ') || l.startsWith('search '));
  return lines.join('\n');
}
